# Generated by Django 4.1.6 on 2023-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hiring',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('telphone', models.CharField(max_length=20)),
                ('Add', models.CharField(max_length=100)),
                ('totalExp', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('portfolio', models.FileField(upload_to='')),
            ],
        ),
    ]
